In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.5'

In [3]:
!wget "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

'wget' is not recognized as an internal or external command,
operable program or batch file.

In [4]:
df = pd.read_csv("D:\\MOHIT\\github\\Machine-Learning\\01-Intro\\car_fuel_efficiency_2026.csv")
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [6]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
df.groupby("origin").fuel_efficiency_mpg.max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [9]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [10]:
df.horsepower.median()

np.float64(254.0)

In [11]:
most_frequent_value = df.horsepower.mode()
most_frequent_value

0    252.0
Name: horsepower, dtype: float64

In [12]:
float(most_frequent_value[0])

252.0

In [13]:
df.horsepower = df.horsepower.fillna(float(most_frequent_value[0]))
df.horsepower.isna().sum()

np.int64(0)

In [14]:
df.horsepower.median()

np.float64(252.0)

In [15]:
df_asia = df[df.origin == 'Asia']
df_asia.count()

model_year             2994
origin                 2994
fuel_type              2994
drivetrain             2994
num_doors              2994
engine_displacement    2994
num_cylinders          2994
horsepower             2994
vehicle_weight         2994
acceleration           2994
fuel_efficiency_mpg    2994
dtype: int64

In [18]:
filtered_df_asia = df_asia[["vehicle_weight","model_year"]].head(7)
filtered_df_asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [20]:
X = filtered_df_asia.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [28]:
trans_X = X.T
trans_X

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [29]:
XTX = trans_X.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [22]:
import numpy as np

In [30]:
XTX.shape

(2, 2)

In [31]:
inv_xtx = np.linalg.inv(XTX)
inv_xtx

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [36]:
y= np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [33]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [34]:
res1=inv_XTX.dot(trans_X)
res1

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [37]:
w=res1.dot(y)
w

array([0.13644777, 0.2327492 ])

In [38]:
w.sum()

np.float64(0.36919696904925486)