In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv")
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [3]:
df.isna().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [5]:
df.dtypes.index

Index(['lead_source', 'industry', 'employment_status', 'location',
       'annual_income', 'number_of_courses_viewed', 'interaction_count',
       'lead_score', 'converted'],
      dtype='str')

In [6]:
df.dtypes == 'str'

lead_source                  True
industry                     True
employment_status            True
location                     True
annual_income               False
number_of_courses_viewed    False
interaction_count           False
lead_score                  False
converted                   False
dtype: bool

In [11]:
categorical_cols = list(df.dtypes[df.dtypes == 'str'].index)
categorical_cols

['lead_source', 'industry', 'employment_status', 'location']

In [13]:
list(df.columns)

['lead_source',
 'industry',
 'employment_status',
 'location',
 'annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score',
 'converted']

In [15]:
df['industry'].isna().sum()

np.int64(240)

In [19]:
for col in list(df.columns):
    if col in categorical_cols:
        df[col] = df[col].fillna('NA')
    else:
        df[col] = df[col].fillna(0)

df.isna().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [20]:
df.describe()

,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,50508.661000,2.089400,4.472600,0.491304,0.576600
std,24927.396949,1.188987,2.435906,0.202969,0.494147
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,35082.750000,1.000000,3.000000,0.350000,0.000000
50%,52613.000000,2.000000,4.000000,0.490000,1.000000
75%,69752.750000,3.000000,6.000000,0.630000,1.000000
max,109886.000000,6.000000,13.000000,0.990000,1.000000

In [21]:
df.mode()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,north_america,0.0,2,4,0.46,1